### ISSUE TITLE
remote access

### ISSUE THREAD

**Issue by arjunashetty** [ioolkos/docker-mzbench#2]
For point 2: Run docker run -d -p 4800:4800 mzbench Note: if you want to have access to a service running on the host (localhost), do something like docker run --network="host" -d -p 4800:4800 mzbench

How can i connect to mzbench UI in docker container installed in remote server from my local ? where can i get the IP address ?

**Comment by arjunashetty** [comment]
@ioolkos  followed all the commands mentioned, still localhost:4800 is getting unable to connect

**Comment by ioolkos** [comment]
I can't tell you the IP of your server. But localhost:4800 will not connect you to that remote server.
Hope you can make it work.

**Comment by arjunashetty** [comment]
yeah, it worked fine @ioolkos , thank you
